version: '3'

services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - 7000:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]

    gmm_server:
        image: danieljodlos/gmm-indexer-erlang
        container_name: gmm_server
        stdin_open: true
        environment:
            - ZONE_ID=zone1
            - GMM_REDIS_HOST=redis
            - GMM_REDIS_PORT=7000
        ports:
            - 8080:8080
        depends_on:
            - redis