version: '3'

services:
    redis-server:
        image: redis:latest
        container_name: redis-server
        ports:
            - 7000:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]

    gmm-server:
        image: danieljodlos/gmm-indexer-erlang
        container_name: gmm-server
        environment:
            - ZONE_ID=zone1
            - GMM_REDIS_HOST=http://redis-server
            - GMM_REDIS_PORT=7000
        depends_on:
            - redis-server
        ports:
            - 8080:8080