name: Erlang CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    container:
      image: erlang:24
    steps:
    - uses: actions/checkout@v2
    - name: Install Erlang/OTP
      run: |
        OTP_VERSION="24.0.2-1"
        UBUNTU_RELEASE="focal"
        DEB_NAME="esl-erlang_${OTP_VERSION}~ubuntu~${UBUNTU_RELEASE}_amd64.deb"
        echo $DEB_NAME
        curl -f https://packages.erlang-solutions.com/erlang/debian/pool/$DEB_NAME -o $DEB_NAME
        sudo dpkg --install $DEB_NAME
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit
    - name: Run CT
      run: cd ./gmm_client && rebar3 ct && cd ..

  lint:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    container:
      image: erlang:24
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Ensure type safety
      run: rebar3 dialyzer
  
  build:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and (maybe) push zone
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: danieljodlos/gmm-indexer-erlang:latest
        
